-- ========================================================================
-- 【UI数据[$$p_nm2d.actor.音效_7]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_nm2d.actor.音效_7
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_nm2d.actor.音效_7
    #CONFIG = {
        'Scale' = 0.83333333333333,
        'Type' = 'EntryModule',
        'X' = -322.86666666667,
        'Y' = 322.96666666667,
    },
    -- <EntryNode>: $$p_nm2d.actor.音效_7.Sound
    'Sound' = {
        'H' = 153.6,
        'Type' = 'EntryNode',
        'W' = 384.66666666667,
        'X' = 571.16666666667,
        'Y' = 51.666666666667,
    },
    -- <EntryNode>: $$p_nm2d.actor.音效_7.root
    'root' = {
        'H' = 188.4,
        'Type' = 'EntryNode',
        'W' = 329.66666666667,
        'X' = 226.0,
        'Y' = -73.666666666667,
    },
}
-- ************************************************************************