-- ========================================================================
-- 【UI数据[$$p_nm2d.actor.音效]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_nm2d.actor.音效
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_nm2d.actor.音效
    #CONFIG = {
        'Scale' = 1.0,
        'Type' = 'EntryModule',
        'X' = -237.16666666667,
        'Y' = 258.91666666667,
    },
    -- <EntryNode>: $$p_nm2d.actor.音效.Sound
    'Sound' = {
        'H' = 154.0,
        'Type' = 'EntryNode',
        'W' = 414.66666666667,
        'X' = 630.33333333333,
        'Y' = 20.833333333333,
    },
    -- <EntryNode>: $$p_nm2d.actor.音效.root
    'root' = {
        'H' = 189.0,
        'Type' = 'EntryNode',
        'W' = 329.66666666667,
        'X' = 276.5,
        'Y' = -12.916666666667,
    },
}
-- ************************************************************************