-- THIS FILE IS AUTO-GENERATED, WOULD BE OVERWRITTEN BY GUI-EDITOR
local component = require '@common.base.gui.component'
local bind = component.bind
local call = component.call
local gui_pkg = require '@common.base.gui.package'
local get_text = gui_pkg.get_text() or get_text
local on_player_prop = require '@common.base.gui.on_player_prop'
local on_unit_prop = require '@common.base.gui.on_unit_prop'
local ctrl_wrapper = require '@common.base.gui.ctrl_wrapper'


local lib_control = require '@lib_control.component'

return gui_pkg.page_template {
    flatten_template = {
        ctrl_wrapper.panel {
            __EDIT_TIME = {
                lock = true,
            },
            disabled = false,
            layout = {
                grow_height = 0,
                grow_width = 0,
                height = -1,
                margin = {
                    right = 10,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                width = -1,
            },
            name = '物品信息_物品信息模板',
            show = true,
        },0,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@smallcard_inventory/image/info_bg_single.png',
            layout = {
                col_self = 'start',
                height = 686,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 435,
            },
            name = '总背景',
            show = true,
            swallow_event = true,
        },1,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            enable_scroll = true,
            layout = {
                col_content = 'start',
                col_self = 'start',
                direction = 'col',
                grow_height = 0,
                grow_width = 0,
                height = 541,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 20,
                },
                row_self = 'center',
                width = 435,
            },
            name = '物品信息背景',
            scroll_color = '#00000000',
            show = true,
        },2,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@smallcard_inventory/image/long_button_equip.png',
            layout = {
                col_self = 'end',
                height = 59,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = -31,
                },
                row_self = 'center',
                width = 373,
            },
            name = '单一按钮',
            show = true,
        },2,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@smallcard_inventory/image/long_button_equip.png',
            layout = {
                col_self = 'end',
                height = 59,
                position = {},
                relative = {
                    [1] = 28,
                    [2] = -31,
                },
                row_self = 'start',
                width = 183,
            },
            name = '双按钮左',
            show = true,
        },2,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@smallcard_inventory/image/long_button_equip.png',
            layout = {
                col_self = 'end',
                height = 59,
                position = {},
                relative = {
                    [1] = -28,
                    [2] = -31,
                },
                row_self = 'end',
                width = 183,
            },
            name = '双按钮右',
            show = true,
        },2,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_content = 'start',
                col_self = 'start',
                direction = 'col',
                grow_height = 0,
                grow_width = 0,
                height = -1,
                position = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                ratio = {},
                row_self = 'start',
                width = 435,
            },
            name = '属性面板',
            show = true,
        },3,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#FAEBD6FF',
                shadow = {
                    color = '#00000040',
                    offset = {
                        [1] = 2,
                        [2] = 2,
                    },
                },
                size = 28,
            },
            layout = {
                col_self = 'center',
                grow_height = 1,
                grow_width = 1,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = -1,
            },
            name = '单一按钮文字',
            show = true,
            text = '使用',
        },4,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#FAEBD6FF',
                shadow = {
                    color = '#00000040',
                    offset = {
                        [1] = 2,
                        [2] = 2,
                    },
                },
                size = 28,
            },
            layout = {
                col_self = 'center',
                grow_height = 1,
                grow_width = 1,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = -1,
            },
            name = '双按钮左文字',
            show = true,
            text = '装备',
        },5,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#FAEBD6FF',
                shadow = {
                    color = '#00000040',
                    offset = {
                        [1] = 2,
                        [2] = 2,
                    },
                },
                size = 28,
            },
            layout = {
                col_self = 'center',
                grow_height = 1,
                grow_width = 1,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = -1,
            },
            name = '双按钮右文字',
            show = true,
            text = '使用',
        },6,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_content = 'start',
                col_self = 'start',
                direction = '',
                grow_height = 0,
                grow_width = 0,
                height = -1,
                margin = {
                    bottom = 28,
                    top = 10,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 435.0,
            },
            name = '标题面板',
            show = true,
        },7,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_self = 'center',
                height = -1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 383,
            },
            name = '属性需求',
            show = true,
        },7,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_content = 'start',
                col_self = '',
                direction = 'col',
                height = -1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = '',
                width = 383,
            },
            name = '物品信息',
            show = true,
        },7,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            image = '@smallcard_inventory/image/item_frame.png',
            layout = {
                col_self = 'start',
                height = 102,
                position = {},
                relative = {
                    [1] = 27,
                    [2] = 0,
                },
                row_self = 'start',
                width = 102,
            },
            name = '图标部分',
            show = true,
        },11,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@smallcard_inventory/image/equiped_bg.png',
            layout = {
                col_self = 'start',
                height = 34,
                position = {},
                relative = {
                    [1] = 26,
                    [2] = -1,
                },
                row_self = 'start',
                width = 86,
            },
            name = '已装备提示',
            show = true,
        },11,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_content = 'start',
                col_self = 'start',
                direction = 'col',
                height = -1,
                position = {},
                relative = {
                    [1] = 145,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 195,
            },
            name = '名称与品质',
            show = true,
        },11,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_self = 'start',
                height = 59,
                position = {},
                relative = {
                    [1] = -25,
                    [2] = 0,
                },
                row_self = 'end',
                width = 59,
            },
            name = '丢弃按钮',
            show = true,
        },11,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                align = 'left',
                bold = true,
                size = 27,
                vertical_align = 'center',
            },
            layout = {
                col_self = 'start',
                height = 38,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 5,
                },
                row_self = 'start',
                width = -1,
            },
            name = '需求文字',
            show = true,
            text = '需求：',
        },12,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_content = 'start',
                col_self = 'center',
                direction = 'col',
                height = -1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 383,
            },
            name = '需求列表底',
            show = true,
        },12,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_content = 'start',
                col_self = '',
                direction = 'col',
                height = -1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = '',
                width = 383,
            },
            name = '上部属性面板',
            show = true,
        },13,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_content = 'start',
                col_self = '',
                direction = 'col',
                height = -1,
                position = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0,
                },
                row_self = '',
                width = 383,
            },
            name = '下部属性面板',
            show = true,
        },13,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                align = 'left',
                color = '#FFFFFFCC',
                size = 28,
                vertical_align = 'top',
            },
            layout = {
                col_self = '',
                height = -1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = '',
                width = 383,
            },
            name = '物品描述',
            show = true,
            text = '这里是物品描述可能会很长很长很长很长很长很长很长很长很长',
        },13,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_self = 'center',
                height = 86,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 86,
            },
            name = '底纹',
            show = true,
        },14,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@smallcard_inventory/image/test_icon.png',
            layout = {
                col_self = 'center',
                height = 86,
                position = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                row_self = 'center',
                width = 86,
            },
            name = '物品图标',
            show = true,
        },14,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                align = 'right',
                bold = true,
                size = 27,
                vertical_align = 'center',
            },
            layout = {
                col_self = 'end',
                height = 33,
                position = {},
                relative = {
                    [1] = -13,
                    [2] = -6,
                },
                row_self = 'end',
                width = -1,
            },
            name = '叠加层数',
            show = true,
            text = '99',
        },14,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@smallcard_inventory/image/品质框=灰色.png',
            layout = {
                col_self = 'center',
                height = 86,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 86,
            },
            name = '品质框',
            show = true,
        },14,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                overflow = 'shrink',
                size = 24,
            },
            layout = {
                col_self = 'center',
                grow_height = 1,
                grow_width = 1,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = -1,
            },
            name = '已装备',
            show = true,
            text = '已装备',
        },15,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                align = 'left',
                bold = true,
                size = 32,
                vertical_align = 'center',
                wrap = true,
            },
            layout = {
                col_self = 'start',
                height = -1,
                margin = {
                    top = 8,
                },
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 195,
            },
            name = '物品名称',
            show = true,
            text = '物品名称可能会很长',
        },16,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                align = 'left',
                bold = true,
                color = '#D72E32FF',
                size = 28,
                vertical_align = 'center',
            },
            layout = {
                col_self = 'center',
                height = -1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 195,
            },
            name = '物品品质',
            show = true,
            text = '物品品质当然也有可能很长',
        },16,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@smallcard_inventory/image/icon_drop.png',
            layout = {
                col_self = 'center',
                height = 46,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 46,
            },
            name = '丢弃按钮图标',
            show = true,
        },17,
        ctrl_wrapper.panel {
            Array = {
                array = 3,
                enable = true,
                template = '$$smallcard_inventory.template@gui_ctrl.UNNAMED_3',
            },
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_content = 'start',
                col_self = '',
                direction = 'col',
                height = -1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = '',
                width = 383,
            },
            name = '需求列表',
            show = true,
        },19,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_self = '',
                height = 22,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = '',
                width = 383,
            },
            name = '尾部',
            show = true,
        },19,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_self = '',
                height = 38,
                margin = {
                    bottom = 11,
                },
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = '',
                width = 383,
            },
            name = '上属性标题面板',
            show = true,
        },20,
        ctrl_wrapper.panel {
            Array = {
                array = 3,
                enable = true,
                template = '$$smallcard_inventory.template@gui_ctrl.UNNAMED_4',
            },
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_content = 'start',
                col_self = 'start',
                direction = 'col',
                height = -1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 383,
            },
            name = '上部属性',
            show = true,
        },20,
        ctrl_wrapper.panel {
            Array = {
                array = 2,
                enable = true,
                template = '$$smallcard_inventory.template@gui_ctrl.UNNAMED_5',
            },
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_content = 'start',
                col_self = 'start',
                direction = 'col',
                height = -1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 383,
            },
            name = '上部词缀描述',
            show = true,
        },20,
        ctrl_wrapper.panel {
            color = '#FFFFFF33',
            disabled = false,
            layout = {
                col_self = '',
                grow_height = 0,
                grow_width = 0,
                height = 2,
                margin = {
                    bottom = 10,
                    top = 9,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = '',
                width = 383,
            },
            name = '上部属性分割线',
            show = true,
        },20,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_self = '',
                height = 38,
                margin = {
                    bottom = 11,
                },
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = '',
                width = 383,
            },
            name = '下属性标题面板',
            show = true,
        },21,
        ctrl_wrapper.panel {
            Array = {
                array = 3,
                enable = true,
                template = '$$smallcard_inventory.template@gui_ctrl.UNNAMED_4',
            },
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_content = 'start',
                col_self = 'start',
                direction = 'col',
                height = -1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 383,
            },
            name = '下部属性',
            show = true,
        },21,
        ctrl_wrapper.panel {
            Array = {
                array = 2,
                enable = true,
                template = '$$smallcard_inventory.template@gui_ctrl.UNNAMED_5',
            },
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_content = 'start',
                col_self = 'start',
                direction = 'col',
                height = -1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 383,
            },
            name = '下部词缀描述',
            show = true,
        },21,
        ctrl_wrapper.panel {
            color = '#FFFFFF33',
            disabled = false,
            layout = {
                col_self = '',
                grow_height = 0,
                grow_width = 0,
                height = 2,
                margin = {
                    bottom = 10,
                    top = 9,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = '',
                width = 383,
            },
            name = '下部属性分割线',
            show = true,
        },21,
        ctrl_wrapper.panel {
            color = '#FFFFFF33',
            disabled = false,
            layout = {
                col_self = '',
                height = 2,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = '',
                width = 383,
            },
            name = '分割线',
            show = true,
        },32,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                align = 'left',
                bold = true,
                size = 27,
                vertical_align = 'bottom',
            },
            layout = {
                col_self = '',
                height = 38,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = '',
                width = 383,
            },
            name = '上属性标题',
            show = true,
            text = '背包：',
        },33,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_self = 'center',
                height = 38,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'end',
                width = -1,
            },
            name = '上属性装备部位面板',
            show = true,
        },33,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                align = 'left',
                bold = true,
                size = 27,
                vertical_align = 'bottom',
            },
            layout = {
                col_self = '',
                height = 38,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = '',
                width = 383,
            },
            name = '下属性标题',
            show = true,
            text = '装备：',
        },37,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_self = 'center',
                height = 38,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'end',
                width = -1,
            },
            name = '下属性装备部位面板',
            show = true,
        },37,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@smallcard_inventory/image/装备部位.png',
            layout = {
                col_self = 'start',
                grow_height = 1,
                grow_width = 1.0,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = -1,
            },
            name = '装备部位背景',
            show = true,
        },43,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#FFFFFFCC',
                size = 24,
            },
            layout = {
                col_self = 'start',
                height = -1,
                margin = {
                    left = 10,
                    right = 10,
                },
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = -1,
            },
            name = '上装备部位',
            show = true,
            text = '副手',
        },43,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@smallcard_inventory/image/装备部位.png',
            layout = {
                col_self = 'start',
                grow_height = 1,
                grow_width = 1.0,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = -1,
            },
            name = '装备部位背景',
            show = true,
        },45,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#FFFFFFCC',
                size = 24,
            },
            layout = {
                col_self = 'start',
                height = -1,
                margin = {
                    left = 10,
                    right = 10,
                },
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = -1,
            },
            name = '下装备部位',
            show = true,
            text = '副手',
        },45,
    }
}