-- THIS FILE IS AUTO-GENERATED, WOULD BE OVERWRITTEN BY GUI-EDITOR
local component = require '@common.base.gui.component'
local bind = component.bind
local call = component.call
local gui_pkg = require '@common.base.gui.package'
local get_text = gui_pkg.get_text() or get_text
local on_player_prop = require '@common.base.gui.on_player_prop'
local on_unit_prop = require '@common.base.gui.on_unit_prop'
local ctrl_wrapper = require '@common.base.gui.ctrl_wrapper'


local gameui = require '@gameui.component'
local smallcard_inventory = require '@smallcard_inventory.component'
local lib_control = require '@lib_control.component'
local lib_game_options = require '@lib_game_options.component'

return gui_pkg.page_template {
    flatten_template = {
        ctrl_wrapper.panel {
            __EDIT_TIME = {
                lock = true,
            },
            disabled = false,
            layout = {
                col_self = 'center',
                grow_height = 1,
                grow_width = 1,
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
            },
            name = 'MainPage',
            show = true,
        },0,
        lib_game_options.设置按钮 {
            disabled = false,
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 100,
                relative = {
                    [1] = -100,
                    [2] = 200,
                },
                row_self = 'end',
                width = 100,
            },
            name = '设置按钮',
            show = false,
        },1,
        smallcard_inventory.背包入口 {
            disabled = false,
            layout = {},
            name = '背包入口2',
            show = false,
        },1,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '',
            layout = {
                col_self = 'center',
                grow_height = 1.0,
                grow_width = 1.0,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = -1,
            },
            name = '开始界面',
            show = false,
        },1,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#000000FF',
                size = 100,
            },
            layout = {
                col_self = 'center',
                height = 1000,
                position = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                row_self = 'end',
                width = 1000,
            },
            name = '测试缓存',
            show = false,
            text = '文本',
        },1,
        ctrl_wrapper.panel {
            color = '#000000C8',
            disabled = false,
            layout = {
                col_self = 'center',
                grow_height = 1.0,
                grow_width = 1.0,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                row_self = 'center',
                width = -1,
            },
            name = '存档相关界面',
            show = false,
        },1,
        ctrl_wrapper.panel {
            color = '#000000C8',
            disabled = false,
            layout = {
                col_self = 'center',
                grow_height = 1.0,
                grow_width = 1.0,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                row_self = 'center',
                width = -1,
            },
            name = '第几天开始界面',
            show = false,
        },1,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_self = 'center',
                grow_height = 1.0,
                grow_width = 1.0,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 1.0,
                    [2] = -1.0,
                },
                row_self = 'center',
                width = -1,
            },
            name = '对话界面',
            show = false,
        },1,
        ctrl_wrapper.panel {
            color = '#050505C8',
            disabled = false,
            layout = {
                col_self = 'center',
                grow_height = 1.0,
                grow_width = 1.0,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = -1,
            },
            name = '游戏标题界面',
            show = false,
        },1,
        ctrl_wrapper.sprites {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            end_frame = 200,
            frame_count = 200,
            image = '@p_nm2d/image/十秒拆帧',
            interval = 1,
            layout = {
                col_self = 'center',
                grow_height = 1.0,
                grow_width = 1.0,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = -1,
            },
            loop = false,
            name = 'LOGO',
            playing = false,
            show = false,
            start_frame = 1,
        },1,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 1073.4033203125,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 2350.0,
            },
            name = '恢复存档界面',
            show = false,
        },1,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/99872eaacdc0e0a0b1986c0ac613caf0.png',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 1000,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1800,
            },
            name = '开场动画2',
            rotate = 0,
            scale = 1,
            show = false,
        },1,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_self = 'center',
                grow_height = 1.0,
                grow_width = 1.0,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = -1,
            },
            name = '开场动画1',
            show = false,
        },1,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/logo_修改后.png',
            layout = {
                col_self = 'center',
                grow_height = 1.0,
                grow_width = 1.0,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'panel9a',
            show = true,
        },4,
        gameui.active_button {
            Asset = 'effect/effect_new/effect_ui/eff_ui_shubiaodianji/particle.effect',
            click_opacity = 1,
            click_scale = 0.85,
            color = '#FFFFFF00',
            disabled = false,
            event = {
                on_mouse_enter = call{client = '@p_nm2d.gui.ui_response.鼠标进入',},
                on_mouse_leave = call{client = '@p_nm2d.gui.ui_response.鼠标离开',},
            },
            image = '@p_nm2d/image/开始游戏-鼠标未移到上面.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 300,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 800,
            },
            name = '开始游戏按钮',
            opacity = 1,
            round_corner_radius = 90,
            show = true,
        },4,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            event = {
                on_mouse_enter = call{client = '@p_nm2d.gui.ui_response.鼠标进入1',},
                on_mouse_leave = call{client = '@p_nm2d.gui.ui_response.鼠标离开1',},
            },
            image = '@p_nm2d/image/继续游戏-白.png',
            layout = {
                col_self = 'center',
                height = 180,
                position = {},
                relative = {
                    [1] = -500,
                    [2] = 0,
                },
                row_self = 'center',
                width = 500,
            },
            name = '查看日历',
            show = true,
        },6,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            event = {
                on_mouse_enter = call{client = '@p_nm2d.gui.ui_response.鼠标进入2',},
                on_mouse_leave = call{client = '@p_nm2d.gui.ui_response.鼠标离开2',},
            },
            image = '@p_nm2d/image/新的开始-白.png',
            layout = {
                col_self = 'center',
                height = 180,
                position = {},
                relative = {
                    [1] = 500,
                    [2] = 0,
                },
                row_self = 'center',
                width = 500,
            },
            name = '新的开始',
            show = true,
        },6,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                size = 100000,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 300.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1800,
            },
            name = '几日',
            show = true,
            text = 'Day·Week    前言',
        },7,
        ctrl_wrapper.panel {
            color = '#E1E1E1C8',
            disabled = false,
            layout = {
                col_self = 'center',
                grow_height = 1.0,
                grow_width = 1.0,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = -1,
            },
            name = '背景版',
            show = false,
        },8,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏外框.png',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 547.22857666016,
                position = {},
                ratio = {},
                relative = {
                    [1] = 1.0,
                    [2] = 123.72375488281,
                },
                row_self = 'start',
                width = 400.0,
            },
            name = '场景状态栏',
            show = true,
        },8,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/返回.png',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 119.23419189453,
                position = {},
                ratio = {},
                relative = {
                    [1] = -0.1246337890625,
                    [2] = 1.1631469726562,
                },
                row_self = 'start',
                width = 395.0,
            },
            name = '退出',
            show = false,
        },8,
        ctrl_wrapper.panel {
            color = '#969191C8',
            disabled = false,
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 72.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 1090,
                    [2] = 200,
                },
                row_self = 'center',
                width = 99.50146484375,
            },
            name = 'panele4',
            show = true,
        },8,
        ctrl_wrapper.panel {
            color = '#969191C8',
            disabled = false,
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 72.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 2053.3481445312,
                    [2] = 707.08892822266,
                },
                row_self = 'start',
                width = 99.50146484375,
            },
            name = 'panele4',
            show = true,
        },8,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = '#FFFFFF',
            disabled = false,
            layout = {
                col_self = 'end',
                height = 100,
                position = {},
                relative = {
                    [1] = -3.617919921875,
                    [2] = -295.5517578125,
                },
                row_self = 'end',
                width = 250,
            },
            name = '跳过界面按钮',
            show = false,
        },8,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            image = '',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 1000,
                position = {},
                ratio = {},
                relative = {
                    [1] = -388.42736816406,
                    [2] = 143.85681152344,
                },
                row_self = 'center',
                width = 800,
            },
            name = '立绘',
            show = true,
        },8,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            image = '@p_nm2d/image/对话框-2340x300.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 300,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 2340,
            },
            name = '文本框',
            opacity = 1,
            show = true,
        },8,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            image = '',
            layout = {
                col_content = 'space_around',
                col_self = 'start',
                direction = 'col',
                grow_height = 0.73,
                grow_width = 0.28,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_content = 'space_between',
                row_self = 'center',
                width = -1,
            },
            name = '选项父控件',
            opacity = 1,
            show = false,
        },8,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                size = 100,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 300.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = -545.74243164062,
                    [2] = -299.29675292969,
                },
                row_self = 'center',
                width = 1252.4614257812,
            },
            name = '标题1',
            show = true,
            text = '',
        },9,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                size = 100,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 300.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 475.7392578125,
                    [2] = -2.8179931640625,
                },
                row_self = 'center',
                width = 1385.2414550781,
            },
            name = '标题2',
            show = true,
            text = '',
        },9,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                size = 50,
            },
            layout = {
                col_self = 'center',
                height = 100,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 500,
            },
            name = '当前进行第几天',
            show = false,
            text = '当前进行第6天',
        },11,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = '#FFFFFF',
            disabled = false,
            layout = {
                col_self = 'end',
                height = 100,
                position = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                row_self = 'center',
                width = 250,
            },
            name = '恢复存档按钮',
            show = false,
        },11,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/选项背景(1).png',
            layout = {
                col_self = 'center',
                height = 700,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1300,
            },
            name = '日历父控件',
            show = true,
        },11,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/a6e183c7ca5a0ac08edfd167e4fa775d.png',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 1000,
                position = {},
                ratio = {},
                relative = {
                    [1] = -60,
                    [2] = -160,
                },
                row_self = 'center',
                width = 1700,
            },
            name = '邮件',
            show = false,
        },12,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/4ee663183f2bb984b17c822460382700.png',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 1237.8725585938,
                position = {},
                ratio = {},
                relative = {
                    [1] = 318,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1691.3422851562,
            },
            name = '收款',
            show = false,
        },12,
        ctrl_wrapper.panel {
            __EDIT_TIME = {
                lock = false,
            },
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_self = 'center',
                grow_height = 0.27777777777778,
                grow_width = 0.53974358974359,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = -128.75756835938,
                    [2] = -205.74267578125,
                },
                row_self = 'center',
                width = -1,
            },
            name = '七日人生',
            show = true,
        },13,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_self = 'center',
                direction = '',
                grow_height = 0.092592592592593,
                grow_width = 0.46538461538462,
                height = -1,
                position = {},
                ratio = {},
                relative = {
                    [1] = 164.69897460938,
                    [2] = 19.950378417969,
                },
                row_self = 'center',
                width = -1,
            },
            name = '你确定这不是bug吗',
            show = true,
        },13,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#000000FF',
                size = 50,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 150,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                row_self = 'center',
                width = 800,
            },
            name = 'label52',
            show = false,
            text = 'START',
        },15,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                size = 30,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 296.44616699219,
                position = {},
                ratio = {},
                relative = {
                    [1] = 2.0,
                    [2] = 2.0,
                },
                row_self = 'start',
                width = 299.0,
            },
            name = 'label59',
            show = false,
            text = '查看日历',
        },16,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                size = 30,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 296.44616699219,
                position = {},
                ratio = {},
                relative = {
                    [1] = 2.0,
                    [2] = 2.0,
                },
                row_self = 'start',
                width = 299.0,
            },
            name = 'label59',
            show = false,
            text = '新的开始',
        },17,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                color = '#000000FF',
                size = 25,
            },
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = -50,
                },
                row_self = 'start',
                width = 400,
            },
            name = 'label61',
            show = false,
            text = '场景状态栏',
        },20,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                align = 'left',
                bold = true,
                color = '#000000FF',
                size = 25,
                vertical_align = 'center',
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 30.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 30.133911132812,
                    [2] = 87.062744140625,
                },
                row_self = 'start',
                width = 340,
            },
            name = '后辈好感度文本',
            show = true,
            text = '陈静好感度：60',
        },20,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                align = 'left',
                bold = true,
                color = '#000000FF',
                size = 25,
                vertical_align = 'center',
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 30.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 29.299133300781,
                    [2] = 160.19665527344,
                },
                row_self = 'start',
                width = 340,
            },
            name = '项目完工度文本',
            show = true,
            text = '项目完工度：0%',
        },20,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                align = 'left',
                bold = true,
                color = '#000000FF',
                size = 25,
                vertical_align = 'center',
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 30.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 30.0,
                    [2] = 239.23680114746,
                },
                row_self = 'start',
                width = 340,
            },
            name = '妻子崩溃度文本',
            show = true,
            text = '妻子崩溃度：50',
        },20,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#000000FF',
                size = 30,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = -40.0,
                    [2] = 466.0,
                },
                row_self = 'end',
                width = 311.52593994141,
            },
            name = '当前场景',
            show = true,
            text = '',
        },20,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                align = 'left',
                bold = true,
                color = '#000000FF',
                size = 25,
                vertical_align = 'center',
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 30.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 29.439575195312,
                    [2] = 369.72512817383,
                },
                row_self = 'start',
                width = 340.61837768555,
            },
            name = '金钱文本',
            show = true,
            text = '金钱：0',
        },20,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-妻子崩溃度文字.png',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 30.0,
                    [2] = 269.0,
                },
                row_self = 'start',
                width = 340,
            },
            name = '崩溃度进度条背景',
            show = true,
        },20,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度文字.png',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 120,
                position = {},
                ratio = {},
                relative = {
                    [1] = 29.534057617188,
                    [2] = 36.397827148438,
                },
                row_self = 'start',
                width = 340,
            },
            name = '好感度进度条背景',
            show = true,
        },20,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-项目进度文字.png',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 29.0,
                    [2] = 189.0,
                },
                row_self = 'start',
                width = 100,
            },
            name = '完工度进度条',
            show = true,
        },20,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-金钱系统文字.png',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 28.75830078125,
                    [2] = 402.40643310547,
                },
                row_self = 'start',
                width = 100,
            },
            name = '金钱进度条父控件',
            show = true,
        },20,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#FF8200FF',
                size = 25,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 50.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = -1.0,
                    [2] = -63.0,
                },
                row_self = 'center',
                width = 150,
            },
            name = '自动播放按钮文本',
            show = true,
            text = '自动播放',
        },22,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/自动播放_黑色(按下前).png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 70,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = -3.0,
                },
                row_self = 'start',
                width = 100.0,
            },
            name = '自动播放按钮',
            show = true,
        },22,
        ctrl_wrapper.label {
            color = '#86868600',
            disabled = false,
            font = {
                bold = true,
                color = '#FF8200FF',
                size = 25,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 50.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = -1.376953125,
                    [2] = -65,
                },
                row_self = 'center',
                width = 150,
            },
            name = '自动播放按钮文本',
            show = true,
            text = '跳过加载',
        },23,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            event = {
                on_click = call{client = '@p_nm2d.gui.ui_response.跳过播放',},
            },
            image = '@p_nm2d/image/跳过_黑色（按下前）.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 72.065444946289,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 1.0,
                },
                row_self = 'start',
                width = 100.0,
            },
            name = '跳过播放按钮',
            show = true,
        },23,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#000000FF',
                size = 25,
            },
            layout = {
                col_self = 'center',
                height = 100,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 250,
            },
            name = 'label65',
            show = true,
            text = '跳过界面',
        },24,
        ctrl_wrapper.panel {
            color = '#7F7F7FFF',
            disabled = false,
            image = '',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 300,
                position = {},
                ratio = {},
                relative = {
                    [1] = -0.34393310546875,
                    [2] = -1.3046875,
                },
                row_self = 'center',
                width = 2340,
            },
            name = '底图',
            opacity = 0.5,
            show = true,
        },26,
        ctrl_wrapper.label {
            color = '#FFFFFF00',
            disabled = false,
            font = {
                align = 'left',
                bold = true,
                size = 50,
                vertical_align = 'center',
            },
            image = '',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 300.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'end',
                width = 1953.7241516113,
            },
            name = '对话文本',
            show = true,
            text = '',
        },26,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            image = '0',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 552.33532714844,
                position = {},
                ratio = {},
                relative = {
                    [1] = -1686.0,
                    [2] = -147.0,
                },
                row_self = 'end',
                width = 772.23864746094,
            },
            name = '头像',
            show = true,
        },26,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#000000FF',
                size = 30,
            },
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = -50.0,
                },
                row_self = 'center',
                width = 800,
            },
            name = '提示',
            show = true,
            text = '点击对话进入下一句对话/跳过文字加载',
        },26,
        ctrl_wrapper.label {
            color = '#C8C2C500',
            disabled = false,
            font = {
                bold = true,
                color = '#060606FF',
                size = 40,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '提示文本',
            round_corner_radius = 180,
            show = true,
            text = '',
        },27,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#0F0F0FFF',
                size = 30,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '当前行动力',
            show = true,
            text = '',
        },27,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/按钮(1).png',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '选项1',
            round_corner_radius = 180,
            show = false,
        },27,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/按钮(1).png',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '选项2',
            round_corner_radius = 180,
            show = false,
        },27,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/按钮(1).png',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '选项3',
            round_corner_radius = 180,
            show = false,
        },27,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/按钮(1).png',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '选项4',
            round_corner_radius = 180,
            show = false,
        },27,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/按钮(1).png',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '选项5',
            round_corner_radius = 180,
            show = false,
        },27,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                color = '#020202FF',
                size = 30,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 100,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 250,
            },
            name = '恢复',
            show = false,
            text = '继续',
        },31,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/星期一.png',
            layout = {
                col_self = 'center',
                height = 300,
                position = {},
                relative = {
                    [1] = -447.0,
                    [2] = -165.0,
                },
                row_self = 'center',
                width = 300,
            },
            name = '星期1',
            show = false,
        },32,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/星期二.png',
            layout = {
                col_self = 'center',
                height = 300,
                position = {},
                relative = {
                    [1] = -147.0,
                    [2] = -165.0,
                },
                row_self = 'center',
                width = 300,
            },
            name = '星期2',
            show = false,
        },32,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/星期三.png',
            layout = {
                col_self = 'center',
                height = 300,
                position = {},
                relative = {
                    [1] = 153.0,
                    [2] = -165.0,
                },
                row_self = 'center',
                width = 300,
            },
            name = '星期3',
            show = false,
        },32,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/星期四.png',
            layout = {
                col_self = 'center',
                height = 300,
                position = {},
                relative = {
                    [1] = 453.0,
                    [2] = -165.0,
                },
                row_self = 'center',
                width = 300,
            },
            name = '星期4',
            show = false,
        },32,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/星期五.png',
            layout = {
                col_self = 'center',
                height = 300,
                position = {},
                relative = {
                    [1] = -447.0,
                    [2] = 135.0,
                },
                row_self = 'center',
                width = 300,
            },
            name = '星期5',
            show = false,
        },32,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/星期六_红.png',
            layout = {
                col_self = 'center',
                height = 300,
                position = {},
                relative = {
                    [1] = -147.0,
                    [2] = 135.0,
                },
                row_self = 'center',
                width = 300,
            },
            name = '星期6',
            show = false,
        },32,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/星期日_红.png',
            layout = {
                col_self = 'center',
                height = 300,
                position = {},
                relative = {
                    [1] = 153.0,
                    [2] = 135.0,
                },
                row_self = 'center',
                width = 300,
            },
            name = '星期7',
            show = false,
        },32,
        gameui.active_button {
            Asset = '',
            click_scale = 0.85,
            color = 'rgba(255,255,255,255)',
            disabled = false,
            event = {
                on_click = call{client = '@p_nm2d.gui.ui_response.返回存档相关界面',},
            },
            image = '@p_nm2d/image/返回.png',
            layout = {
                col_self = 'center',
                height = 300,
                position = {},
                relative = {
                    [1] = 453.01440429688,
                    [2] = 135.044921875,
                },
                row_self = 'center',
                width = 300,
            },
            name = '日历返回',
            show = true,
        },32,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/七.png',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 1000,
                position = {},
                ratio = {},
                relative = {
                    [1] = -400,
                    [2] = 100,
                },
                row_self = 'center',
                width = 1500,
            },
            name = '七',
            scale = 1,
            show = false,
        },35,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/日.png',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 1000,
                position = {},
                ratio = {},
                relative = {
                    [1] = -150,
                    [2] = 100,
                },
                row_self = 'center',
                width = 1500,
            },
            name = '日',
            show = false,
        },35,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/人.png',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 1000,
                position = {},
                ratio = {},
                relative = {
                    [1] = 100,
                    [2] = 100,
                },
                row_self = 'center',
                width = 1500,
            },
            name = '人',
            show = false,
        },35,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/生.png',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 1000,
                position = {},
                ratio = {},
                relative = {
                    [1] = 350,
                    [2] = 100,
                },
                row_self = 'center',
                width = 1500,
            },
            name = '生',
            show = false,
        },35,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/-.png',
            layout = {
                col_self = 'center',
                height = 1000,
                position = {},
                relative = {
                    [1] = -500,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1500,
            },
            name = '杠',
            show = false,
        },36,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/你.png',
            layout = {
                col_self = 'center',
                height = 1000,
                position = {},
                relative = {
                    [1] = -400,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1500,
            },
            name = '你',
            show = false,
        },36,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/确.png',
            layout = {
                col_self = 'center',
                height = 1000,
                position = {},
                relative = {
                    [1] = -300,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1500,
            },
            name = '确',
            scale = 1,
            show = false,
        },36,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/定.png',
            layout = {
                col_self = 'center',
                height = 1000,
                position = {},
                relative = {
                    [1] = -200,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1500,
            },
            name = '定',
            scale = 1,
            show = false,
        },36,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/，.png',
            layout = {
                col_self = 'center',
                height = 1000,
                position = {},
                relative = {
                    [1] = -100,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1500,
            },
            name = '逗号',
            show = false,
        },36,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/这.png',
            layout = {
                col_self = 'center',
                height = 1000,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1500,
            },
            name = '这',
            scale = 1,
            show = false,
        },36,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/不.png',
            layout = {
                col_self = 'center',
                height = 1000,
                position = {},
                relative = {
                    [1] = 100,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1500,
            },
            name = '不',
            scale = 1,
            show = false,
        },36,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/是.png',
            layout = {
                col_self = 'center',
                height = 1000,
                position = {},
                relative = {
                    [1] = 200,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1500,
            },
            name = '是',
            scale = 1,
            show = false,
        },36,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/b.png',
            layout = {
                col_self = 'center',
                height = 1000,
                position = {},
                relative = {
                    [1] = 300,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1500,
            },
            name = 'B',
            scale = 1,
            show = false,
        },36,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/u.png',
            layout = {
                col_self = 'center',
                height = 1000,
                position = {},
                relative = {
                    [1] = 400,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1500,
            },
            name = 'U',
            scale = 1,
            show = false,
        },36,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/g.png',
            layout = {
                col_self = 'center',
                height = 1000,
                position = {},
                relative = {
                    [1] = 500,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1500,
            },
            name = 'G',
            scale = 1,
            show = false,
        },36,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/吗.png',
            layout = {
                col_self = 'center',
                height = 1000,
                position = {},
                relative = {
                    [1] = 600,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1500,
            },
            name = '吗',
            scale = 1,
            show = false,
        },36,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/？.png',
            layout = {
                col_self = 'center',
                height = 1000,
                position = {},
                relative = {
                    [1] = 700,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1500,
            },
            name = '问号',
            scale = 1,
            show = false,
        },36,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_self = 'center',
                direction = 'row',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 50,
                },
                row_content = 'start',
                row_self = 'center',
                width = 340,
            },
            name = '妻子崩溃度父控件',
            show = true,
        },46,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_content = 'space_around',
                col_self = 'start',
                direction = 'row',
                grow_height = 0,
                grow_width = 0,
                height = 36.0,
                padding = {
                    bottom = 0,
                    left = 0,
                    right = 0,
                    top = 0,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = 99.0,
                    [2] = 84.0,
                },
                row_content = 'space_around',
                row_self = 'start',
                width = 240,
            },
            name = '好感度进度条父控件',
            show = true,
        },47,
        ctrl_wrapper.panel {
            color = '#FFFFFF00',
            disabled = false,
            layout = {
                col_content = 'end',
                col_self = 'start',
                direction = 'row',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 100,
                    [2] = 0,
                },
                row_content = 'start',
                row_self = 'start',
                width = 242.15354919434,
            },
            name = '完工度进度条父控件',
            show = true,
        },48,
        ctrl_wrapper.panel {
            color = '#0D0D0D64',
            disabled = false,
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 50.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 100,
                    [2] = 0,
                },
                row_self = 'start',
                width = 240,
            },
            name = '金钱进度条背景',
            show = true,
        },49,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#FF9100FF',
                size = 30,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 137.83514404297,
                    [2] = 98.432968139648,
                },
                row_self = 'start',
                width = 500,
            },
            name = '说话者名称',
            show = true,
            text = '',
        },57,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#1B1B1BFF',
                size = 25,
            },
            layout = {
                col_self = 'center',
                height = 400,
                position = {},
                relative = {
                    [1] = -52.037231445312,
                    [2] = 49.435424804688,
                },
                row_self = 'center',
                width = 400,
            },
            name = 'label5f',
            show = false,
            text = '我是立绘',
        },57,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#0F0F0FFF',
                size = 30,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 12,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '选项文本',
            show = true,
            text = '选择',
        },61,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#0F0F0FFF',
                size = 20,
            },
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = -15,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '描述文本',
            show = true,
            text = '描述',
        },61,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#0F0F0FFF',
                size = 30,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 12,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '选项文本',
            show = true,
            text = '选择',
        },62,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#0F0F0FFF',
                size = 20,
            },
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = -15,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '描述文本',
            show = true,
            text = '描述',
        },62,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#0F0F0FFF',
                size = 30,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 12,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '选项文本',
            show = true,
            text = '选择',
        },63,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#0F0F0FFF',
                size = 20,
            },
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = -15,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '描述文本',
            show = true,
            text = '描述',
        },63,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#0F0F0FFF',
                size = 30,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 12,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '选项文本',
            show = true,
            text = '选择',
        },64,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#0F0F0FFF',
                size = 20,
            },
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = -15,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '描述文本',
            show = true,
            text = '描述',
        },64,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#0F0F0FFF',
                size = 30,
            },
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 12,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '选项文本',
            show = true,
            text = '选择',
        },65,
        ctrl_wrapper.label {
            disabled = false,
            font = {
                bold = true,
                color = '#0F0F0FFF',
                size = 20,
            },
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 50,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = -15,
                },
                row_self = 'center',
                width = 600.0,
            },
            name = '描述文本',
            show = true,
            text = '描述',
        },65,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-妻子崩溃度符号表示.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 34,
            },
            name = '崩溃度1',
            show = false,
        },92,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-妻子崩溃度符号表示.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 34,
            },
            name = '崩溃度2',
            show = false,
        },92,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-妻子崩溃度符号表示.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 34,
            },
            name = '崩溃度3',
            show = false,
        },92,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-妻子崩溃度符号表示.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 34,
            },
            name = '崩溃度4',
            show = false,
        },92,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-妻子崩溃度符号表示.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 34,
            },
            name = '崩溃度5',
            show = false,
        },92,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-妻子崩溃度符号表示.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 34,
            },
            name = '崩溃度6',
            show = false,
        },92,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-妻子崩溃度符号表示.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 34,
            },
            name = '崩溃度7',
            show = false,
        },92,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-妻子崩溃度符号表示.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 34,
            },
            name = '崩溃度8',
            show = false,
        },92,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-妻子崩溃度符号表示.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 34,
            },
            name = '崩溃度9',
            show = false,
        },92,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-妻子崩溃度符号表示.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 34,
            },
            name = '崩溃度10',
            show = false,
        },92,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度有进度条.png',
            layout = {
                col_self = 'end',
                height = 9,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度1',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度有进度条.png',
            layout = {
                col_self = 'end',
                height = 9,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度2',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度有进度条.png',
            layout = {
                col_self = 'end',
                height = 9,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度3',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度有进度条.png',
            layout = {
                col_self = 'end',
                height = 9,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度4',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度有进度条.png',
            layout = {
                col_self = 'end',
                height = 9,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度5',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度有进度条.png',
            layout = {
                col_self = 'end',
                height = 9,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度6',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度有进度条.png',
            layout = {
                col_self = 'end',
                height = 9,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度7',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度有进度条.png',
            layout = {
                col_self = 'end',
                height = 9,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度8',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度有进度条.png',
            layout = {
                col_self = 'end',
                height = 9,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度9',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度10',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度11',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度12',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度13',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度14',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度15',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度16',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度17',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度18',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度19',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度20',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度21',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度22',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度23',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度24',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-陈静好感度无进度条.png',
            layout = {
                col_self = 'end',
                grow_height = 0,
                grow_width = 0,
                height = 9,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 9,
            },
            name = '好感度25',
            show = true,
        },93,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-项目进度符号.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 24,
            },
            name = '完工度1',
            show = false,
        },94,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-项目进度符号.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 24,
            },
            name = '完工度2',
            show = false,
        },94,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-项目进度符号.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 24,
            },
            name = '完工度3',
            show = false,
        },94,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-项目进度符号.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 24,
            },
            name = '完工度4',
            show = false,
        },94,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-项目进度符号.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 24,
            },
            name = '完工度5',
            show = false,
        },94,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-项目进度符号.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 24,
            },
            name = '完工度6',
            show = false,
        },94,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-项目进度符号.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 24,
            },
            name = '完工度7',
            show = false,
        },94,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-项目进度符号.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 24,
            },
            name = '完工度8',
            show = false,
        },94,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-项目进度符号.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 24,
            },
            name = '完工度9',
            show = false,
        },94,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            disabled = false,
            image = '@p_nm2d/image/状态栏-项目进度符号.png',
            layout = {
                col_self = 'start',
                height = 50,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 24,
            },
            name = '完工度10',
            show = false,
        },94,
        ctrl_wrapper.panel {
            color = '#0D0D0DC8',
            disabled = false,
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 50.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                row_self = 'start',
                width = 0,
            },
            name = '金钱进度条',
            show = true,
            transition = {
                size = {
                    func = {
                        [1] = 0,
                        [2] = 0,
                        [3] = 1,
                        [4] = 1,
                    },
                    time = 0,
                },
            },
        },95,
    }
}