-- ========================================================================
-- 【UI数据[$$p_nm2d.actor.音效_10]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_nm2d.actor.音效_10
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_nm2d.actor.音效_10
    #CONFIG = {
        'Scale' = 1.0,
        'Type' = 'EntryModule',
        'X' = 73.5,
        'Y' = 311.0,
    },
    -- <EntryNode>: $$p_nm2d.actor.音效_10.Sound
    'Sound' = {
        'H' = 154.0,
        'Type' = 'EntryNode',
        'W' = 414.0,
        'X' = 496.16666666667,
        'Y' = 30.833333333333,
    },
    -- <EntryNode>: $$p_nm2d.actor.音效_10.root
    'root' = {
        'H' = 189.0,
        'Type' = 'EntryNode',
        'W' = 330.0,
        'X' = 163.5,
        'Y' = -24.5,
    },
}
-- ************************************************************************