-- ========================================================================
-- 【UI数据[$$p_nm2d.actor.音效_5]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_nm2d.actor.音效_5
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_nm2d.actor.音效_5
    #CONFIG = {
        'Scale' = 1.2,
        'Type' = 'EntryModule',
        'X' = -331.66666666666,
        'Y' = 229.5,
    },
    -- <EntryNode>: $$p_nm2d.actor.音效_5.Sound
    'Sound' = {
        'H' = 154.16666666667,
        'Type' = 'EntryNode',
        'W' = 383.0,
        'X' = 667.0,
        'Y' = 55.0,
    },
    -- <EntryNode>: $$p_nm2d.actor.音效_5.root
    'root' = {
        'H' = 188.33333333333,
        'Type' = 'EntryNode',
        'W' = 329.66666666667,
        'X' = 246.0,
        'Y' = -57.0,
    },
}
-- ************************************************************************