-- ========================================================================
-- 【UI数据[$$p_nm2d.actor.音效_19]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_nm2d.actor.音效_19
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_nm2d.actor.音效_19
    #CONFIG = {
        'Scale' = 0.69444444444444,
        'Type' = 'EntryModule',
        'X' = 487.61777777778,
        'Y' = 536.86666666667,
    },
    -- <EntryNode>: $$p_nm2d.actor.音效_19.Sound
    'Sound' = {
        'H' = 154.08,
        'Type' = 'EntryNode',
        'W' = 419.68,
        'X' = -36.63333333333,
        'Y' = 169.07333333333,
    },
    -- <EntryNode>: $$p_nm2d.actor.音效_19.root
    'root' = {
        'H' = 188.64,
        'Type' = 'EntryNode',
        'W' = 333.28,
        'X' = 3.5,
        'Y' = -40.5,
    },
}
-- ************************************************************************