{
    "ElementName":"FunctionDefine",
    "actions":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"FunctionCall",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"",
                "flags":{
                },
                "funcSource":{
                    "ElementName":"Source",
                    "targetUninit":{
                        "id":"FunctionDefine:增强版立即完成当前文字显示:952197765",
                        "packageName":"p_nm2d",
                        "s_or_c":"client"
                    }
                },
                "parameters":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":"",
                "typeParameters":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                }
            }
        ]
    },
    "breakPointInfo":{
        "disabled":false,
        "hasBreakPoint":false,
        "type":2
    },
    "defaultResetParameterCount":0,
    "description":"",
    "displayName":"func",
    "flags":{
        "hideConfig":true,
        "noSelf":true,
        "pop":true,
        "unchangeName":true,
        "unchangeParameter":true
    },
    "id":"FunctionDefine:func:988586741",
    "keyword":"",
    "label":"默认",
    "name":"func",
    "packageName":"__validator__",
    "parameters":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"ctrl",
                "flags":{
                },
                "id":"Variable:ctrl:2506215111",
                "keyword":"",
                "label":"默认",
                "name":"ctrl",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"InstanceType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "source":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ_gameui_gui_ctrl_active_button",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeArgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            },
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"mouse_btn_id",
                "flags":{
                },
                "id":"Variable:mouse_btn_id:622602953",
                "keyword":"",
                "label":"默认",
                "name":"mouse_btn_id",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"SimpleType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"数值",
                    "flags":{
                    },
                    "name":"number",
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":""
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            }
        ]
    },
    "realReturnType":{
        "ElementName":"SimpleType",
        "breakPointInfo":{
            "disabled":false,
            "hasBreakPoint":false,
            "type":2
        },
        "displayName":"void",
        "flags":{
        },
        "name":"void",
        "staticWarningMsgs":{
            "__TYPE":"Array",
            "contents":{
            }
        },
        "tips":""
    },
    "s_or_c":"client",
    "staticWarningMsgs":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "subsections":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "tips":"",
    "typeParameters":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "typeParametersExtends":{
        "__TYPE":"Map",
        "contents":{
        }
    },
    "uiText":"",
    "v2_version":0.900000,
    "variables":{
        "__TYPE":"Array",
        "contents":{
        }
    }
}