{
    "ElementName":"FunctionDefine",
    "actions":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"FunctionCall",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"",
                "flags":{
                },
                "funcSource":{
                    "ElementName":"Source",
                    "targetUninit":{
                        "id":"FunctionDefine:GUI淡出:214831215",
                        "packageName":"p_nm2d",
                        "s_or_c":"client"
                    }
                },
                "parameters":{
                    "__TYPE":"Array",
                    "contents":[
                        {
                            "ElementName":"SourceValue",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "staticWarningMsgs":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            },
                            "tips":"",
                            "valueSource":{
                                "ElementName":"Source",
                                "targetUninit":{
                                    "id":"Variable:新变量:2535301705",
                                    "packageName":"__validator__",
                                    "s_or_c":"client"
                                }
                            }
                        }
                    ]
                },
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":"",
                "typeParameters":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                }
            },
            {
                "ElementName":"FunctionCall",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"",
                "flags":{
                },
                "funcSource":{
                    "ElementName":"Source",
                    "targetUninit":{
                        "id":"FunctionDefine:timer_wait2480930816.0",
                        "packageName":"__client__",
                        "s_or_c":"client"
                    }
                },
                "parameters":{
                    "__TYPE":"Array",
                    "contents":[
                        {
                            "ElementName":"Instant",
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"",
                            "flags":{
                            },
                            "staticWarningMsgs":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            },
                            "tips":"",
                            "type":{
                                "ElementName":"SimpleType",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"数值",
                                "flags":{
                                },
                                "name":"number",
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":""
                            },
                            "value":1
                        },
                        {
                            "ElementName":"ArrowFunction",
                            "actions":{
                                "__TYPE":"Array",
                                "contents":[
                                    {
                                        "ElementName":"FunctionCall",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"",
                                        "flags":{
                                        },
                                        "funcSource":{
                                            "ElementName":"Source",
                                            "targetUninit":{
                                                "id":"FunctionDefine:GUI淡入:2357081245",
                                                "packageName":"p_nm2d",
                                                "s_or_c":"client"
                                            }
                                        },
                                        "parameters":{
                                            "__TYPE":"Array",
                                            "contents":[
                                                {
                                                    "ElementName":"Index",
                                                    "baseValue":{
                                                        "ElementName":"Index",
                                                        "baseValue":{
                                                            "ElementName":"SourceValue",
                                                            "breakPointInfo":{
                                                                "disabled":false,
                                                                "hasBreakPoint":false,
                                                                "type":2
                                                            },
                                                            "displayName":"",
                                                            "flags":{
                                                            },
                                                            "staticWarningMsgs":{
                                                                "__TYPE":"Array",
                                                                "contents":{
                                                                }
                                                            },
                                                            "tips":"",
                                                            "valueSource":{
                                                                "ElementName":"Source",
                                                                "targetUninit":{
                                                                    "id":"Class:panel类:938577522",
                                                                    "packageName":"p_nm2d",
                                                                    "s_or_c":"client"
                                                                }
                                                            }
                                                        },
                                                        "breakPointInfo":{
                                                            "disabled":false,
                                                            "hasBreakPoint":false,
                                                            "type":2
                                                        },
                                                        "displayName":"",
                                                        "flags":{
                                                        },
                                                        "indexSource":{
                                                            "ElementName":"Source",
                                                            "targetUninit":{
                                                                "id":"Class:panel类:938577522, ClassProperty:单例",
                                                                "packageName":"p_nm2d",
                                                                "s_or_c":"client"
                                                            }
                                                        },
                                                        "staticWarningMsgs":{
                                                            "__TYPE":"Array",
                                                            "contents":{
                                                            }
                                                        },
                                                        "tips":""
                                                    },
                                                    "breakPointInfo":{
                                                        "disabled":false,
                                                        "hasBreakPoint":false,
                                                        "type":2
                                                    },
                                                    "displayName":"",
                                                    "flags":{
                                                        "fromOop":true
                                                    },
                                                    "indexSource":{
                                                        "ElementName":"Source",
                                                        "targetUninit":{
                                                            "id":"Class:panel类:938577522, ClassProperty:存档相关界面",
                                                            "packageName":"p_nm2d",
                                                            "s_or_c":"client"
                                                        }
                                                    },
                                                    "staticWarningMsgs":{
                                                        "__TYPE":"Array",
                                                        "contents":{
                                                        }
                                                    },
                                                    "tips":""
                                                }
                                            ]
                                        },
                                        "staticWarningMsgs":{
                                            "__TYPE":"Array",
                                            "contents":{
                                            }
                                        },
                                        "tips":"",
                                        "typeParameters":{
                                            "__TYPE":"Array",
                                            "contents":{
                                            }
                                        }
                                    }
                                ]
                            },
                            "breakPointInfo":{
                                "disabled":false,
                                "hasBreakPoint":false,
                                "type":2
                            },
                            "displayName":"回调函数",
                            "flags":{
                                "enableDisplayName":true,
                                "pop":true
                            },
                            "packageName":"",
                            "parameters":{
                                "__TYPE":"Array",
                                "contents":[
                                    {
                                        "ElementName":"Parameter",
                                        "breakPointInfo":{
                                            "disabled":false,
                                            "hasBreakPoint":false,
                                            "type":2
                                        },
                                        "displayName":"计时器",
                                        "flags":{
                                            "enableDisplayName":true
                                        },
                                        "id":"Variable:计时器:2234403081",
                                        "keyword":"",
                                        "label":"默认",
                                        "name":"计时器",
                                        "packageName":"",
                                        "realType":{
                                            "ElementName":"InstanceType",
                                            "breakPointInfo":{
                                                "disabled":false,
                                                "hasBreakPoint":false,
                                                "type":2
                                            },
                                            "displayName":"",
                                            "flags":{
                                            },
                                            "source":{
                                                "ElementName":"Source",
                                                "targetUninit":{
                                                    "id":"Class:Timer",
                                                    "packageName":"__client__",
                                                    "s_or_c":"client"
                                                }
                                            },
                                            "staticWarningMsgs":{
                                                "__TYPE":"Array",
                                                "contents":{
                                                }
                                            },
                                            "tips":"",
                                            "typeArgs":{
                                                "__TYPE":"Array",
                                                "contents":{
                                                }
                                            }
                                        },
                                        "s_or_c":"client",
                                        "staticWarningMsgs":{
                                            "__TYPE":"Array",
                                            "contents":{
                                            }
                                        },
                                        "tips":""
                                    }
                                ]
                            },
                            "realReturnType":{
                                "ElementName":"SimpleType",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"void",
                                "flags":{
                                },
                                "name":"void",
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":""
                            },
                            "s_or_c":"client",
                            "staticWarningMsgs":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            },
                            "subsections":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            },
                            "tips":"",
                            "typeParameters":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            },
                            "typeParametersExtends":{
                                "__TYPE":"Map",
                                "contents":{
                                }
                            },
                            "variables":{
                                "__TYPE":"Array",
                                "contents":{
                                }
                            }
                        }
                    ]
                },
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":"",
                "typeParameters":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                }
            }
        ]
    },
    "breakPointInfo":{
        "disabled":false,
        "hasBreakPoint":false,
        "type":2
    },
    "defaultResetParameterCount":0,
    "description":"",
    "displayName":"func",
    "flags":{
        "hideConfig":true,
        "noSelf":true,
        "pop":true,
        "unchangeName":true,
        "unchangeParameter":true
    },
    "id":"FunctionDefine:func:1790510489",
    "keyword":"",
    "label":"默认",
    "linkspace":"",
    "name":"func",
    "packageName":"__validator__",
    "parameters":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"ctrl",
                "flags":{
                },
                "id":"Variable:ctrl:2347950259",
                "keyword":"",
                "label":"默认",
                "name":"ctrl",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"InstanceType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "source":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ_gameui_gui_ctrl_active_button",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeArgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            },
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"mouse_btn_id",
                "flags":{
                },
                "id":"Variable:mouse_btn_id:3621160286",
                "keyword":"",
                "label":"默认",
                "name":"mouse_btn_id",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"SimpleType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"数值",
                    "flags":{
                    },
                    "name":"number",
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":""
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            }
        ]
    },
    "rankOrder":0,
    "realReturnType":{
        "ElementName":"SimpleType",
        "breakPointInfo":{
            "disabled":false,
            "hasBreakPoint":false,
            "type":2
        },
        "displayName":"void",
        "flags":{
        },
        "name":"void",
        "staticWarningMsgs":{
            "__TYPE":"Array",
            "contents":{
            }
        },
        "tips":""
    },
    "s_or_c":"client",
    "staticWarningMsgs":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "subsections":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "tips":"",
    "typeParameters":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "typeParametersExtends":{
        "__TYPE":"Map",
        "contents":{
        }
    },
    "uiText":"",
    "v2_version":0.900000,
    "variables":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"Variable",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "defaultValue":{
                    "ElementName":"FunctionCall",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "funcSource":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"FunctionDefine:gui_get_part4248698880.0",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "parameters":{
                        "__TYPE":"Array",
                        "contents":[
                            {
                                "ElementName":"FunctionCall",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                    "enableDisplayName":true
                                },
                                "funcSource":{
                                    "ElementName":"Source",
                                    "targetUninit":{
                                        "id":"FunctionDefine:gui_get_main_page1445330944",
                                        "packageName":"__client__",
                                        "s_or_c":"client"
                                    }
                                },
                                "parameters":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":"",
                                "typeParameters":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                }
                            },
                            {
                                "ElementName":"Instant",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"",
                                "flags":{
                                    "enableDisplayName":true
                                },
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":"",
                                "type":{
                                    "ElementName":"SimpleType",
                                    "breakPointInfo":{
                                        "disabled":false,
                                        "hasBreakPoint":false,
                                        "type":2
                                    },
                                    "displayName":"字符串",
                                    "flags":{
                                    },
                                    "name":"string",
                                    "staticWarningMsgs":{
                                        "__TYPE":"Array",
                                        "contents":{
                                        }
                                    },
                                    "tips":""
                                },
                                "value":"恢复存档界面"
                            }
                        ]
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeParameters":{
                        "__TYPE":"Array",
                        "contents":[
                            {
                                "ElementName":"SimpleType",
                                "breakPointInfo":{
                                    "disabled":false,
                                    "hasBreakPoint":false,
                                    "type":2
                                },
                                "displayName":"任意",
                                "flags":{
                                },
                                "name":"any",
                                "staticWarningMsgs":{
                                    "__TYPE":"Array",
                                    "contents":{
                                    }
                                },
                                "tips":""
                            }
                        ]
                    }
                },
                "displayName":"恢复存档界面",
                "flags":{
                },
                "id":"Variable:新变量:2535301705",
                "keyword":"",
                "label":"默认",
                "name":"恢复存档界面",
                "packageName":"__validator__",
                "rankOrder":0,
                "realType":{
                    "ElementName":"InstanceType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "source":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ__gui_ctrl_panel",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeArgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            }
        ]
    }
}