{
    "ElementName":"FunctionDefine",
    "actions":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"SetValue",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"",
                "flags":{
                },
                "left":{
                    "ElementName":"Index",
                    "baseValue":{
                        "ElementName":"SourceValue",
                        "breakPointInfo":{
                            "disabled":false,
                            "hasBreakPoint":false,
                            "type":2
                        },
                        "displayName":"",
                        "flags":{
                        },
                        "staticWarningMsgs":{
                            "__TYPE":"Array",
                            "contents":{
                            }
                        },
                        "tips":"",
                        "valueSource":{
                            "ElementName":"Source",
                            "targetUninit":{
                                "id":"Variable:ctrl:3321310364",
                                "packageName":"__validator__",
                                "s_or_c":"client"
                            }
                        }
                    },
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                        "fromOop":true
                    },
                    "indexSource":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ_gameui_gui_ctrl_active_button, ClassProperty:image",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":""
                },
                "right":{
                    "ElementName":"Instant",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "type":{
                        "ElementName":"SimpleType",
                        "breakPointInfo":{
                            "disabled":false,
                            "hasBreakPoint":false,
                            "type":2
                        },
                        "displayName":"字符串",
                        "flags":{
                        },
                        "name":"string",
                        "staticWarningMsgs":{
                            "__TYPE":"Array",
                            "contents":{
                            }
                        },
                        "tips":""
                    },
                    "value":"@p_nm2d/image/新的开始-白.png"
                },
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            }
        ]
    },
    "breakPointInfo":{
        "disabled":false,
        "hasBreakPoint":false,
        "type":2
    },
    "defaultResetParameterCount":0,
    "description":"",
    "displayName":"func",
    "flags":{
        "hideConfig":true,
        "noSelf":true,
        "pop":true,
        "unchangeName":true,
        "unchangeParameter":true
    },
    "id":"FunctionDefine:func:2686865535",
    "keyword":"",
    "label":"默认",
    "linkspace":"",
    "name":"func",
    "packageName":"__validator__",
    "parameters":{
        "__TYPE":"Array",
        "contents":[
            {
                "ElementName":"Parameter",
                "breakPointInfo":{
                    "disabled":false,
                    "hasBreakPoint":false,
                    "type":2
                },
                "displayName":"ctrl",
                "flags":{
                },
                "id":"Variable:ctrl:3321310364",
                "keyword":"",
                "label":"默认",
                "name":"ctrl",
                "packageName":"__validator__",
                "realType":{
                    "ElementName":"InstanceType",
                    "breakPointInfo":{
                        "disabled":false,
                        "hasBreakPoint":false,
                        "type":2
                    },
                    "displayName":"",
                    "flags":{
                    },
                    "source":{
                        "ElementName":"Source",
                        "targetUninit":{
                            "id":"Class:_OBJ_gameui_gui_ctrl_active_button",
                            "packageName":"__client__",
                            "s_or_c":"client"
                        }
                    },
                    "staticWarningMsgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    },
                    "tips":"",
                    "typeArgs":{
                        "__TYPE":"Array",
                        "contents":{
                        }
                    }
                },
                "s_or_c":"client",
                "staticWarningMsgs":{
                    "__TYPE":"Array",
                    "contents":{
                    }
                },
                "tips":""
            }
        ]
    },
    "rankOrder":0,
    "realReturnType":{
        "ElementName":"SimpleType",
        "breakPointInfo":{
            "disabled":false,
            "hasBreakPoint":false,
            "type":2
        },
        "displayName":"void",
        "flags":{
        },
        "name":"void",
        "staticWarningMsgs":{
            "__TYPE":"Array",
            "contents":{
            }
        },
        "tips":""
    },
    "s_or_c":"client",
    "staticWarningMsgs":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "subsections":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "tips":"",
    "typeParameters":{
        "__TYPE":"Array",
        "contents":{
        }
    },
    "typeParametersExtends":{
        "__TYPE":"Map",
        "contents":{
        }
    },
    "uiText":"",
    "v2_version":0.900000,
    "variables":{
        "__TYPE":"Array",
        "contents":{
        }
    }
}