-- ========================================================================
-- 【UI数据[$$p_nm2d.actor.音效_30]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$p_nm2d.actor.音效_30
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$p_nm2d.actor.音效_30
    #CONFIG = {
        'Scale' = 1.2,
        'Type' = 'EntryModule',
        'X' = -351.56666666667,
        'Y' = 209.58333333333,
    },
    -- <EntryNode>: $$p_nm2d.actor.音效_30.Sound
    'Sound' = {
        'H' = 154.16666666667,
        'Type' = 'EntryNode',
        'W' = 380.8,
        'X' = 496.16666666667,
        'Y' = 30.833333333333,
    },
    -- <EntryNode>: $$p_nm2d.actor.音效_30.root
    'root' = {
        'H' = 189.0,
        'Type' = 'EntryNode',
        'W' = 329.66666666667,
        'X' = 3.5,
        'Y' = -40.5,
    },
}
-- ************************************************************************