-- ========================================================================
-- 【实例模块[map_config.dflt]配置文件】
-- 说明：
--   1、#NIL代表强制赋值为nil，无视继承值。
--   2、#CONFIG代表当前配置文件对应实例模块自身的配置。
-- ========================================================================

-- ************************************************************************
[#CONFIG]
'Version' = 14
-- ************************************************************************

-- ************************************************************************
-- [$$.map_config.dflt.ResourceList]
['ResourceList']
'IsPatch' = true
'Version' = 1
'NodeType' = '$$.map_config.ResourceList'
'Inherit' = '$$.template@map_config.ResourceList.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'Actor' = {
            1 = '$$p_nm2d.actor.音效.root',
            2 = '$$p_nm2d.actor.音效_1.root',
            3 = '$$p_nm2d.actor.音效_2.root',
            4 = '$$p_nm2d.actor.音效_3.root',
            5 = '$$p_nm2d.actor.音效_4.root',
            6 = '$$p_nm2d.actor.音效_5.root',
            7 = '$$p_nm2d.actor.音效_6.root',
            8 = '$$p_nm2d.actor.音效_7.root',
            9 = '$$p_nm2d.actor.音效_8.root',
            10 = '$$p_nm2d.actor.音效_9.root',
            11 = '$$p_nm2d.actor.音效_10.root',
            12 = '$$p_nm2d.actor.1.root',
        },
        'ResSound' = {
            1 = 'sound/_user/yinxiao09_sasd.ogg',
            2 = 'sound/_user/jianpanyinxiao10_8egd.ogg',
            3 = 'sound/_user/hangdongjiemianyinle_qb3c.ogg',
            4 = 'sound/_user/xindiantuyinxiao_7gmd.ogg',
            5 = 'sound/_user/piangangzhenyang_clld.ogg',
            6 = 'sound/_user/day1_4hkd.ogg',
            7 = 'sound/_user/jianpanyinxiao_5zx1.ogg',
            8 = 'sound/_user/yinxiao5_qr4d.ogg',
            9 = 'sound/_user/yinxiao6_wakd.ogg',
            10 = 'sound/_user/yinxiao7_xyhc.ogg',
            11 = 'sound/_user/uiyinxiao8_mgbd.ogg',
        },
    },
}
'UIConfig' = {
}
-- ************************************************************************

-- ************************************************************************
-- [$$.map_config.dflt.root]
['root']
'IsPatch' = true
'Version' = 1
'NodeType' = '$$.map_config.MapConfig'
'Inherit' = '$$.template@map_config.MapConfig.root'
'Data' = {
    'Editor' = {
    },
    'Game' = {
        'player_setting' = {
            0 = {
                1 = 'computer',
                2 = 100,
                'Neutral' = true,
                'DisplayName' = '[EntryNode][$$.map_config.dflt.root].Data.Game.player_setting[0].DisplayName',
            },
            1 = {
                1 = 'user',
                2 = 1,
                'Neutral' = false,
                'DisplayName' = '[EntryNode][$$.map_config.dflt.root].Data.Game.player_setting[1].DisplayName',
            },
            2 = {
                1 = 'computer',
                2 = 2,
                'Neutral' = false,
                'DisplayName' = '[EntryNode][$$.map_config.dflt.root].Data.Game.player_setting[2].DisplayName',
            },
            3 = #FORCE_NIL,
            4 = #FORCE_NIL,
            5 = #FORCE_NIL,
            7 = #FORCE_NIL,
            99 = #FORCE_NIL,
        },
        'TeamNames' = {
            1 = '[EntryNode][$$.map_config.dflt.root].Data.Game.TeamNames[1]',
            2 = '[EntryNode][$$.map_config.dflt.root].Data.Game.TeamNames[2]',
            100 = '[EntryNode][$$.map_config.dflt.root].Data.Game.TeamNames[100]',
        },
        'opened_slots' = {
            'IsOverwrite' = true,
        },
        'ai_slots' = {
            1 = 2,
            2 = #FORCE_NIL,
            3 = #FORCE_NIL,
            4 = #FORCE_NIL,
            'IsOverwrite' = true,
            #IS_OVERWRITE = true,
        },
    },
}
'UIConfig' = {
}
-- ************************************************************************