-- ========================================================================
-- 【UI数据[$$.map_config.dflt]配置文件】
-- 说明：
--   1、#CONFIG代表实例模块自身对应的UI。
--   2、Data下Key为字符串的子项为实例记录或引用的公共实例模块的主节点UI数据。
--   3、Data下Key为数字的子项为实例记录快捷方式、引用的公共实例模块快捷方式或注释。
-- ========================================================================

-- ************************************************************************
-- $$.map_config.dflt
[UIData]
'Version' = 2
'EntryData' = {
    -- <EntryModule>: $$.map_config.dflt
    #CONFIG = {
        'Scale' = 0.99999999999999,
        'X' = -748.79404444445,
        'Y' = 226.36435555556,
    },
    -- <EntryNode>: $$.map_config.dflt.ResourceList
    'ResourceList' = {
        'H' = 714.0,
        'W' = 528.0,
    },
    -- <EntryNode>: $$.map_config.dflt.root
    'root' = {
        'H' = 643.68,
        'X' = 350.0,
        'Y' = 522.0,
    },
    -- <Lnk>: $$p_nm2d.actor.1.root
    '$$p_nm2d.actor.1.root' = {
        'H' = 77.760000000001,
        'Type' = 'Lnk',
        'W' = 208,
        'X' = 1288.6477777778,
        'Y' = 899.34044444445,
    },
    -- <Lnk>: $$p_nm2d.actor.音效.root
    '$$p_nm2d.actor.音效.root' = {
        'H' = 79.000000000001,
        'Type' = 'Lnk',
        'W' = 208,
        'X' = 1237.6477777778,
        'Y' = -118.65955555556,
    },
    -- <Lnk>: $$p_nm2d.actor.音效_1.root
    '$$p_nm2d.actor.音效_1.root' = {
        'H' = 79.000000000001,
        'Type' = 'Lnk',
        'W' = 208,
        'X' = 1240.6477777778,
        'Y' = -38.659555555557,
    },
    -- <Lnk>: $$p_nm2d.actor.音效_10.root
    '$$p_nm2d.actor.音效_10.root' = {
        'H' = 79.200000000001,
        'Type' = 'Lnk',
        'W' = 208,
        'X' = 1283.6477777778,
        'Y' = 798.34044444445,
    },
    -- <Lnk>: $$p_nm2d.actor.音效_2.root
    '$$p_nm2d.actor.音效_2.root' = {
        'H' = 79.000000000001,
        'Type' = 'Lnk',
        'W' = 208,
        'X' = 1247.6477777778,
        'Y' = 107.34044444444,
    },
    -- <Lnk>: $$p_nm2d.actor.音效_3.root
    '$$p_nm2d.actor.音效_3.root' = {
        'H' = 79.000000000001,
        'Type' = 'Lnk',
        'W' = 208,
        'X' = 1244.6477777778,
        'Y' = 211.34044444444,
    },
    -- <Lnk>: $$p_nm2d.actor.音效_4.root
    '$$p_nm2d.actor.音效_4.root' = {
        'H' = 79.000000000001,
        'Type' = 'Lnk',
        'W' = 208,
        'X' = 1239.6477777778,
        'Y' = 299.34044444445,
    },
    -- <Lnk>: $$p_nm2d.actor.音效_5.root
    '$$p_nm2d.actor.音效_5.root' = {
        'H' = 79.000000000001,
        'Type' = 'Lnk',
        'W' = 208,
        'X' = 1249.6477777778,
        'Y' = 389.34044444445,
    },
    -- <Lnk>: $$p_nm2d.actor.音效_6.root
    '$$p_nm2d.actor.音效_6.root' = {
        'H' = 79.000000000001,
        'Type' = 'Lnk',
        'W' = 208,
        'X' = 1263.6477777778,
        'Y' = 471.34044444445,
    },
    -- <Lnk>: $$p_nm2d.actor.音效_7.root
    '$$p_nm2d.actor.音效_7.root' = {
        'H' = 79.000000000001,
        'Type' = 'Lnk',
        'W' = 208,
        'X' = 1262.6477777778,
        'Y' = 534.34044444445,
    },
    -- <Lnk>: $$p_nm2d.actor.音效_8.root
    '$$p_nm2d.actor.音效_8.root' = {
        'H' = 79.200000000001,
        'Type' = 'Lnk',
        'W' = 208,
        'X' = 1274.6477777778,
        'Y' = 621.34044444445,
    },
    -- <Lnk>: $$p_nm2d.actor.音效_9.root
    '$$p_nm2d.actor.音效_9.root' = {
        'H' = 79.200000000001,
        'Type' = 'Lnk',
        'W' = 208,
        'X' = 1276.6477777778,
        'Y' = 710.34044444445,
    },
}
-- ************************************************************************